package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SueConceptoGrupoDetalle generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_grupo_detalle")
public class SueConceptoGrupoDetalle implements java.io.Serializable {

	private long grupoDetalleId;
	private SueConceptoLey sueConceptoLey;
	private SueConceptoGrupo sueConceptoGrupo;

	public SueConceptoGrupoDetalle() {
	}

	public SueConceptoGrupoDetalle(long grupoDetalleId,
			SueConceptoLey sueConceptoLey, SueConceptoGrupo sueConceptoGrupo) {
		this.grupoDetalleId = grupoDetalleId;
		this.sueConceptoLey = sueConceptoLey;
		this.sueConceptoGrupo = sueConceptoGrupo;
	}

	@Id
	@Column(name = "grupo_detalle_id", unique = true, nullable = false)
	public long getGrupoDetalleId() {
		return this.grupoDetalleId;
	}

	public void setGrupoDetalleId(long grupoDetalleId) {
		this.grupoDetalleId = grupoDetalleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grupo_id", nullable = false)
	public SueConceptoGrupo getSueConceptoGrupo() {
		return this.sueConceptoGrupo;
	}

	public void setSueConceptoGrupo(SueConceptoGrupo sueConceptoGrupo) {
		this.sueConceptoGrupo = sueConceptoGrupo;
	}

}
