package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoDatos generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_datos")
public class SueConceptoDatos implements java.io.Serializable {

	private long conceptoDatoId;
	private SueConceptoLey sueConceptoLey;
	private SueConceptoDatos sueConceptoDatos;
	private long depId;
	private String nombreCorto;
	private String codigo;
	private String subcodigo;
	private Date FDesde;
	private Date FHasta;
	private char vigente;
	private String observa;
	private Date FCarga;
	private long usrCarga;
	private Date FModif;
	private Long usrModif;
	private Integer ordenVisual;
	private Set<SueConceptoDatos> sueConceptoDatoses = new HashSet<SueConceptoDatos>(
			0);

	public SueConceptoDatos() {
	}

	public SueConceptoDatos(long conceptoDatoId, SueConceptoLey sueConceptoLey,
			long depId, String nombreCorto, String codigo, String subcodigo,
			Date FDesde, char vigente, Date FCarga, long usrCarga) {
		this.conceptoDatoId = conceptoDatoId;
		this.sueConceptoLey = sueConceptoLey;
		this.depId = depId;
		this.nombreCorto = nombreCorto;
		this.codigo = codigo;
		this.subcodigo = subcodigo;
		this.FDesde = FDesde;
		this.vigente = vigente;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
	}

	public SueConceptoDatos(long conceptoDatoId, SueConceptoLey sueConceptoLey,
			SueConceptoDatos sueConceptoDatos, long depId, String nombreCorto,
			String codigo, String subcodigo, Date FDesde, Date FHasta,
			char vigente, String observa, Date FCarga, long usrCarga,
			Date FModif, Long usrModif, Integer ordenVisual,
			Set<SueConceptoDatos> sueConceptoDatoses) {
		this.conceptoDatoId = conceptoDatoId;
		this.sueConceptoLey = sueConceptoLey;
		this.sueConceptoDatos = sueConceptoDatos;
		this.depId = depId;
		this.nombreCorto = nombreCorto;
		this.codigo = codigo;
		this.subcodigo = subcodigo;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.vigente = vigente;
		this.observa = observa;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
		this.FModif = FModif;
		this.usrModif = usrModif;
		this.ordenVisual = ordenVisual;
		this.sueConceptoDatoses = sueConceptoDatoses;
	}

	@Id
	@Column(name = "concepto_dato_id", unique = true, nullable = false)
	public long getConceptoDatoId() {
		return this.conceptoDatoId;
	}

	public void setConceptoDatoId(long conceptoDatoId) {
		this.conceptoDatoId = conceptoDatoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_dato_pad_id")
	public SueConceptoDatos getSueConceptoDatos() {
		return this.sueConceptoDatos;
	}

	public void setSueConceptoDatos(SueConceptoDatos sueConceptoDatos) {
		this.sueConceptoDatos = sueConceptoDatos;
	}

	@Column(name = "dep_id", nullable = false)
	public long getDepId() {
		return this.depId;
	}

	public void setDepId(long depId) {
		this.depId = depId;
	}

	@Column(name = "nombre_corto", nullable = false, length = 150)
	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	@Column(name = "codigo", nullable = false, length = 30)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "subcodigo", nullable = false, length = 20)
	public String getSubcodigo() {
		return this.subcodigo;
	}

	public void setSubcodigo(String subcodigo) {
		this.subcodigo = subcodigo;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

	@Column(name = "vigente", nullable = false, length = 1)
	public char getVigente() {
		return this.vigente;
	}

	public void setVigente(char vigente) {
		this.vigente = vigente;
	}

	@Column(name = "observa")
	public String getObserva() {
		return this.observa;
	}

	public void setObserva(String observa) {
		this.observa = observa;
	}

	@Column(name = "f_carga", nullable = false, length = 35)
	public Date getFCarga() {
		return this.FCarga;
	}

	public void setFCarga(Date FCarga) {
		this.FCarga = FCarga;
	}

	@Column(name = "usr_carga", nullable = false)
	public long getUsrCarga() {
		return this.usrCarga;
	}

	public void setUsrCarga(long usrCarga) {
		this.usrCarga = usrCarga;
	}

	@Column(name = "f_modif", length = 35)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Column(name = "usr_modif")
	public Long getUsrModif() {
		return this.usrModif;
	}

	public void setUsrModif(Long usrModif) {
		this.usrModif = usrModif;
	}

	@Column(name = "orden_visual")
	public Integer getOrdenVisual() {
		return this.ordenVisual;
	}

	public void setOrdenVisual(Integer ordenVisual) {
		this.ordenVisual = ordenVisual;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoDatos")
	public Set<SueConceptoDatos> getSueConceptoDatoses() {
		return this.sueConceptoDatoses;
	}

	public void setSueConceptoDatoses(Set<SueConceptoDatos> sueConceptoDatoses) {
		this.sueConceptoDatoses = sueConceptoDatoses;
	}

}
