package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoPlantilla generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_plantilla")
public class SueConceptoPlantilla implements java.io.Serializable {

	private long plantillaId;
	private Long depId;
	private String leyId;
	private String nombre;
	private String descrip;
	private Set<SueConceptoPlantillaDetalle> sueConceptoPlantillaDetalles = new HashSet<SueConceptoPlantillaDetalle>(
			0);

	public SueConceptoPlantilla() {
	}

	public SueConceptoPlantilla(long plantillaId, String leyId, String nombre) {
		this.plantillaId = plantillaId;
		this.leyId = leyId;
		this.nombre = nombre;
	}

	public SueConceptoPlantilla(long plantillaId, Long depId, String leyId,
			String nombre, String descrip,
			Set<SueConceptoPlantillaDetalle> sueConceptoPlantillaDetalles) {
		this.plantillaId = plantillaId;
		this.depId = depId;
		this.leyId = leyId;
		this.nombre = nombre;
		this.descrip = descrip;
		this.sueConceptoPlantillaDetalles = sueConceptoPlantillaDetalles;
	}

	@Id
	@Column(name = "plantilla_id", unique = true, nullable = false)
	public long getPlantillaId() {
		return this.plantillaId;
	}

	public void setPlantillaId(long plantillaId) {
		this.plantillaId = plantillaId;
	}

	@Column(name = "dep_id")
	public Long getDepId() {
		return this.depId;
	}

	public void setDepId(Long depId) {
		this.depId = depId;
	}

	@Column(name = "ley_id", nullable = false, length = 4)
	public String getLeyId() {
		return this.leyId;
	}

	public void setLeyId(String leyId) {
		this.leyId = leyId;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descrip", length = 250)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoPlantilla")
	public Set<SueConceptoPlantillaDetalle> getSueConceptoPlantillaDetalles() {
		return this.sueConceptoPlantillaDetalles;
	}

	public void setSueConceptoPlantillaDetalles(
			Set<SueConceptoPlantillaDetalle> sueConceptoPlantillaDetalles) {
		this.sueConceptoPlantillaDetalles = sueConceptoPlantillaDetalles;
	}

}
