package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoGrupo generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_grupo")
public class SueConceptoGrupo implements java.io.Serializable {

	private String grupoId;
	private String descrip;
	private Set<SueConceptoGrupoDetalle> sueConceptoGrupoDetalles = new HashSet<SueConceptoGrupoDetalle>(
			0);

	public SueConceptoGrupo() {
	}

	public SueConceptoGrupo(String grupoId, String descrip) {
		this.grupoId = grupoId;
		this.descrip = descrip;
	}

	public SueConceptoGrupo(String grupoId, String descrip,
			Set<SueConceptoGrupoDetalle> sueConceptoGrupoDetalles) {
		this.grupoId = grupoId;
		this.descrip = descrip;
		this.sueConceptoGrupoDetalles = sueConceptoGrupoDetalles;
	}

	@Id
	@Column(name = "grupo_id", unique = true, nullable = false, length = 15)
	public String getGrupoId() {
		return this.grupoId;
	}

	public void setGrupoId(String grupoId) {
		this.grupoId = grupoId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoGrupo")
	public Set<SueConceptoGrupoDetalle> getSueConceptoGrupoDetalles() {
		return this.sueConceptoGrupoDetalles;
	}

	public void setSueConceptoGrupoDetalles(
			Set<SueConceptoGrupoDetalle> sueConceptoGrupoDetalles) {
		this.sueConceptoGrupoDetalles = sueConceptoGrupoDetalles;
	}

}
