package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9



import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * SueConceptoTipo generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_tipo")
public class SueConceptoTipo implements java.io.Serializable {

	private String tipoConceptoId;
	private String descrip;
	private Set<SueConcepto> sueConceptos = new HashSet<SueConcepto>(0);

	public SueConceptoTipo() {
	}

	public SueConceptoTipo(String tipoConceptoId, String descrip) {
		this.tipoConceptoId = tipoConceptoId;
		this.descrip = descrip;
	}

	public SueConceptoTipo(String tipoConceptoId, String descrip,
			Set<SueConcepto> sueConceptos) {
		this.tipoConceptoId = tipoConceptoId;
		this.descrip = descrip;
		
	}

	@Id
	@Column(name = "tipo_concepto_id", unique = true, nullable = false, length = 15)
	public String getTipoConceptoId() {
		return this.tipoConceptoId;
	}

	public void setTipoConceptoId(String tipoConceptoId) {
		this.tipoConceptoId = tipoConceptoId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}
	
	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoTipo")
	public Set<SueConcepto> getSueConceptos() {
		return this.sueConceptos;
	}

	public void setSueConceptos(Set<SueConcepto> sueConceptos) {
		this.sueConceptos = sueConceptos;
	}



}
