package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoAplicacion generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_aplicacion")
public class SueConceptoAplicacion implements java.io.Serializable {

	private String tipoAplicacionId;
	private String descrip;
	
	public SueConceptoAplicacion() {
	}

	public SueConceptoAplicacion(String tipoAplicacionId, String descrip) {
		this.tipoAplicacionId = tipoAplicacionId;
		this.descrip = descrip;
	}

	

	@Id
	@Column(name = "tipo_aplicacion_id", unique = true, nullable = false, length = 15)
	public String getTipoAplicacionId() {
		return this.tipoAplicacionId;
	}

	public void setTipoAplicacionId(String tipoAplicacionId) {
		this.tipoAplicacionId = tipoAplicacionId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	

	
}
