package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * SueConcepto generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto")
public class SueConcepto implements java.io.Serializable {

	private long conceptoId;
	private SueConceptoModalidad sueConceptoModalidad;
	private SueConceptoTipo sueConceptoTipo;
	private SueConceptoAplicacion sueConceptoAplicacion;
	private SueConceptoCaracter sueConceptoCaracter;
	private String descripGral;
	private int ordenVisual;
	private Date FDesde;
	private Date FHasta;
	private char vigente;
	private String observa;
	private Date FCarga;
	private long usrCarga;
	private Date FModif;
	private Long usrModif;
	private String claveTag;
	private List<SueConceptoLey> sueConceptoLeies = new ArrayList<SueConceptoLey>();

	public SueConcepto() {
	}

	public SueConcepto(long conceptoId,
			SueConceptoModalidad sueConceptoModalidad,
			SueConceptoTipo sueConceptoTipo,
			SueConceptoAplicacion sueConceptoAplicacion,
			SueConceptoCaracter sueConceptoCaracter, String descripGral,
			int ordenVisual, Date FDesde, char vigente, Date FCarga,
			long usrCarga, String claveTag) {
		this.conceptoId = conceptoId;
		this.sueConceptoModalidad = sueConceptoModalidad;
		this.sueConceptoTipo = sueConceptoTipo;
		this.sueConceptoAplicacion = sueConceptoAplicacion;
		this.sueConceptoCaracter = sueConceptoCaracter;
		this.descripGral = descripGral;
		this.ordenVisual = ordenVisual;
		this.FDesde = FDesde;
		this.vigente = vigente;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
		this.claveTag = claveTag;
	}

	public SueConcepto(long conceptoId,
			SueConceptoModalidad sueConceptoModalidad,
			SueConceptoTipo sueConceptoTipo,
			SueConceptoAplicacion sueConceptoAplicacion,
			SueConceptoCaracter sueConceptoCaracter, String descripGral,
			int ordenVisual, Date FDesde, Date FHasta, char vigente,
			String observa, Date FCarga, long usrCarga, Date FModif,
			Long usrModif, String claveTag, Set<SueConceptoLey> sueConceptoLeies) {
		this.conceptoId = conceptoId;
		this.sueConceptoModalidad = sueConceptoModalidad;
		this.sueConceptoTipo = sueConceptoTipo;
		this.sueConceptoAplicacion = sueConceptoAplicacion;
		this.sueConceptoCaracter = sueConceptoCaracter;
		this.descripGral = descripGral;
		this.ordenVisual = ordenVisual;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.vigente = vigente;
		this.observa = observa;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
		this.FModif = FModif;
		this.usrModif = usrModif;
		this.claveTag = claveTag;
	
	}
	
	@SequenceGenerator(name="seq_sue_concepto", sequenceName = "sue_concepto_id_seq", allocationSize = 1)
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "seq_sue_concepto")
	@Column(name = "concepto_id", unique = true, nullable = false)
	public long getConceptoId() {
		return this.conceptoId;
	}

	public void setConceptoId(long conceptoId) {
		this.conceptoId = conceptoId;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modalidad_id", nullable = false)
	public SueConceptoModalidad getSueConceptoModalidad() {
		return this.sueConceptoModalidad;
	}

	public void setSueConceptoModalidad(
			SueConceptoModalidad sueConceptoModalidad) {
		this.sueConceptoModalidad = sueConceptoModalidad;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_concepto_id", nullable = false)
	public SueConceptoTipo getSueConceptoTipo() {
		return this.sueConceptoTipo;
	}

	public void setSueConceptoTipo(SueConceptoTipo sueConceptoTipo) {
		this.sueConceptoTipo = sueConceptoTipo;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_aplicacion_id", nullable = false)
	public SueConceptoAplicacion getSueConceptoAplicacion() {
		return this.sueConceptoAplicacion;
	}

	public void setSueConceptoAplicacion(
			SueConceptoAplicacion sueConceptoAplicacion) {
		this.sueConceptoAplicacion = sueConceptoAplicacion;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caracter_id", nullable = false)
	public SueConceptoCaracter getSueConceptoCaracter() {
		return this.sueConceptoCaracter;
	}

	public void setSueConceptoCaracter(SueConceptoCaracter sueConceptoCaracter) {
		this.sueConceptoCaracter = sueConceptoCaracter;
	}

	@Column(name = "descrip_gral", nullable = false, length = 150)
	public String getDescripGral() {
		return this.descripGral;
	}

	public void setDescripGral(String descripGral) {
		this.descripGral = descripGral;
	}

	@Column(name = "orden_visual", nullable = false)
	public int getOrdenVisual() {
		return this.ordenVisual;
	}

	public void setOrdenVisual(int ordenVisual) {
		this.ordenVisual = ordenVisual;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

	@Column(name = "vigente", nullable = false, length = 1)
	public char getVigente() {
		return this.vigente;
	}

	public void setVigente(char vigente) {
		this.vigente = vigente;
	}

	@Column(name = "observa")
	public String getObserva() {
		return this.observa;
	}

	public void setObserva(String observa) {
		this.observa = observa;
	}

	@Column(name = "f_carga", nullable = false, length = 35)
	public Date getFCarga() {
		return this.FCarga;
	}

	public void setFCarga(Date FCarga) {
		this.FCarga = FCarga;
	}

	@Column(name = "usr_carga", nullable = false)
	public long getUsrCarga() {
		return this.usrCarga;
	}

	public void setUsrCarga(long usrCarga) {
		this.usrCarga = usrCarga;
	}
	
	@Column(name = "f_modif", length = 35)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}
	
	@Column(name = "usr_modif")
	public Long getUsrModif() {
		return this.usrModif;
	}

	public void setUsrModif(Long usrModif) {
		this.usrModif = usrModif;
	}
	
	@Column(name = "clave_tag", nullable = false, length = 100)
	public String getClaveTag() {
		return this.claveTag;
	}

	public void setClaveTag(String claveTag) {
		this.claveTag = claveTag;
	}	
	
	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "sueConcepto")
	public List<SueConceptoLey> getSueConceptoLeies() {
		return sueConceptoLeies;
	}

	public void setSueConceptoLeies(List<SueConceptoLey> sueConceptoLeies) {
		this.sueConceptoLeies = sueConceptoLeies;
	}
	

}
