package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SueConceptoFrecuencia generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_frecuencia")
public class SueConceptoFrecuencia implements java.io.Serializable {

	private long conceptoFrecuenciaId;
	private SueConceptoLey sueConceptoLey;
	private short mesAplicacion;

	public SueConceptoFrecuencia() {
	}

	public SueConceptoFrecuencia(long conceptoFrecuenciaId,
			SueConceptoLey sueConceptoLey, short mesAplicacion) {
		this.conceptoFrecuenciaId = conceptoFrecuenciaId;
		this.sueConceptoLey = sueConceptoLey;
		this.mesAplicacion = mesAplicacion;
	}

	@Id
	@Column(name = "concepto_frecuencia_id", unique = true, nullable = false)
	public long getConceptoFrecuenciaId() {
		return this.conceptoFrecuenciaId;
	}

	public void setConceptoFrecuenciaId(long conceptoFrecuenciaId) {
		this.conceptoFrecuenciaId = conceptoFrecuenciaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@Column(name = "mes_aplicacion", nullable = false)
	public short getMesAplicacion() {
		return this.mesAplicacion;
	}

	public void setMesAplicacion(short mesAplicacion) {
		this.mesAplicacion = mesAplicacion;
	}

}
