package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoCalcExp generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_calc_exp")
public class SueConceptoCalcExp implements java.io.Serializable {

	private long conceptoCalcExpId;
	private SueConceptoLey sueConceptoLey;
	private SueConceptoCalcExp sueConceptoCalcExp;
	private String descripCalculo;
	private String expGramatica;
	private Date FDesde;
	private Date FHasta;
	private char vigente;
	private String observa;
	private Date FCarga;
	private long usrCarga;
	private Date FModif;
	private Long usrModif;
	private Set<SueConceptoCalculo> sueConceptoCalculos = new HashSet<SueConceptoCalculo>(
			0);
	private Set<SueConceptoCalcExp> sueConceptoCalcExps = new HashSet<SueConceptoCalcExp>(
			0);

	public SueConceptoCalcExp() {
	}

	public SueConceptoCalcExp(long conceptoCalcExpId,
			SueConceptoLey sueConceptoLey, String expGramatica, Date FDesde,
			char vigente, Date FCarga, long usrCarga) {
		this.conceptoCalcExpId = conceptoCalcExpId;
		this.sueConceptoLey = sueConceptoLey;
		this.expGramatica = expGramatica;
		this.FDesde = FDesde;
		this.vigente = vigente;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
	}

	public SueConceptoCalcExp(long conceptoCalcExpId,
			SueConceptoLey sueConceptoLey,
			SueConceptoCalcExp sueConceptoCalcExp, String descripCalculo,
			String expGramatica, Date FDesde, Date FHasta, char vigente,
			String observa, Date FCarga, long usrCarga, Date FModif,
			Long usrModif, Set<SueConceptoCalculo> sueConceptoCalculos,
			Set<SueConceptoCalcExp> sueConceptoCalcExps) {
		this.conceptoCalcExpId = conceptoCalcExpId;
		this.sueConceptoLey = sueConceptoLey;
		this.sueConceptoCalcExp = sueConceptoCalcExp;
		this.descripCalculo = descripCalculo;
		this.expGramatica = expGramatica;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.vigente = vigente;
		this.observa = observa;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
		this.FModif = FModif;
		this.usrModif = usrModif;
		this.sueConceptoCalculos = sueConceptoCalculos;
		this.sueConceptoCalcExps = sueConceptoCalcExps;
	}

	@Id
	@Column(name = "concepto_calc_exp_id", unique = true, nullable = false)
	public long getConceptoCalcExpId() {
		return this.conceptoCalcExpId;
	}

	public void setConceptoCalcExpId(long conceptoCalcExpId) {
		this.conceptoCalcExpId = conceptoCalcExpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_calc_exp_pad_id")
	public SueConceptoCalcExp getSueConceptoCalcExp() {
		return this.sueConceptoCalcExp;
	}

	public void setSueConceptoCalcExp(SueConceptoCalcExp sueConceptoCalcExp) {
		this.sueConceptoCalcExp = sueConceptoCalcExp;
	}

	@Column(name = "descrip_calculo")
	public String getDescripCalculo() {
		return this.descripCalculo;
	}

	public void setDescripCalculo(String descripCalculo) {
		this.descripCalculo = descripCalculo;
	}

	@Column(name = "exp_gramatica", nullable = false)
	public String getExpGramatica() {
		return this.expGramatica;
	}

	public void setExpGramatica(String expGramatica) {
		this.expGramatica = expGramatica;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

	@Column(name = "vigente", nullable = false, length = 1)
	public char getVigente() {
		return this.vigente;
	}

	public void setVigente(char vigente) {
		this.vigente = vigente;
	}

	@Column(name = "observa")
	public String getObserva() {
		return this.observa;
	}

	public void setObserva(String observa) {
		this.observa = observa;
	}

	@Column(name = "f_carga", nullable = false, length = 35)
	public Date getFCarga() {
		return this.FCarga;
	}

	public void setFCarga(Date FCarga) {
		this.FCarga = FCarga;
	}

	@Column(name = "usr_carga", nullable = false)
	public long getUsrCarga() {
		return this.usrCarga;
	}

	public void setUsrCarga(long usrCarga) {
		this.usrCarga = usrCarga;
	}

	@Column(name = "f_modif", length = 35)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Column(name = "usr_modif")
	public Long getUsrModif() {
		return this.usrModif;
	}

	public void setUsrModif(Long usrModif) {
		this.usrModif = usrModif;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoCalcExp")
	public Set<SueConceptoCalculo> getSueConceptoCalculos() {
		return this.sueConceptoCalculos;
	}

	public void setSueConceptoCalculos(
			Set<SueConceptoCalculo> sueConceptoCalculos) {
		this.sueConceptoCalculos = sueConceptoCalculos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoCalcExp")
	public Set<SueConceptoCalcExp> getSueConceptoCalcExps() {
		return this.sueConceptoCalcExps;
	}

	public void setSueConceptoCalcExps(
			Set<SueConceptoCalcExp> sueConceptoCalcExps) {
		this.sueConceptoCalcExps = sueConceptoCalcExps;
	}

}
