package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * SueConceptoCaracter generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_caracter")
public class SueConceptoCaracter implements java.io.Serializable {

	private String caracterId;
	private String descrip;
	private Set<SueConcepto> sueConceptos = new HashSet<SueConcepto>(0);

	public SueConceptoCaracter() {
	}

	public SueConceptoCaracter(String caracterId, String descrip) {
		this.caracterId = caracterId;
		this.descrip = descrip;
	}

	public SueConceptoCaracter(String caracterId, String descrip,
			Set<SueConcepto> sueConceptos) {
		this.caracterId = caracterId;
		this.descrip = descrip;
		this.sueConceptos = sueConceptos;
	}

	@Id
	@Column(name = "caracter_id", unique = true, nullable = false, length = 15)
	public String getCaracterId() {
		return this.caracterId;
	}

	public void setCaracterId(String caracterId) {
		this.caracterId = caracterId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}
	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoCaracter")
	public Set<SueConcepto> getSueConceptos() {
		return this.sueConceptos;
	}

	public void setSueConceptos(Set<SueConcepto> sueConceptos) {
		this.sueConceptos = sueConceptos;
	}

}
