package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoLey generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_ley")
public class SueConceptoLey implements java.io.Serializable {

	private long conceptoLeyId;
	private SueConcepto sueConcepto;
	private String leyId;
	private Date FDesde;
	private Date FHasta;
	private char vigente;
	private Date FCarga;
	private long usrCarga;
	private Date FModif;
	private Long usrModif;
	private int ordenVisual;
	private int ordenCalculo;
	

	public SueConceptoLey() {
	}

	
	

	@Id
	@Column(name = "concepto_ley_id", unique = true, nullable = false)
	public long getConceptoLeyId() {
		return this.conceptoLeyId;
	}

	public void setConceptoLeyId(long conceptoLeyId) {
		this.conceptoLeyId = conceptoLeyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_id", nullable = false)
	public SueConcepto getSueConcepto() {
		return this.sueConcepto;
	}

	public void setSueConcepto(SueConcepto sueConcepto) {
		this.sueConcepto = sueConcepto;
	}

	@Column(name = "ley_id", nullable = false, length = 4)
	public String getLeyId() {
		return this.leyId;
	}

	public void setLeyId(String leyId) {
		this.leyId = leyId;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

	@Column(name = "vigente", nullable = false, length = 1)
	public char getVigente() {
		return this.vigente;
	}

	public void setVigente(char vigente) {
		this.vigente = vigente;
	}

	@Column(name = "f_carga", nullable = false, length = 35)
	public Date getFCarga() {
		return this.FCarga;
	}

	public void setFCarga(Date FCarga) {
		this.FCarga = FCarga;
	}

	@Column(name = "usr_carga", nullable = false)
	public long getUsrCarga() {
		return this.usrCarga;
	}

	public void setUsrCarga(long usrCarga) {
		this.usrCarga = usrCarga;
	}

	@Column(name = "f_modif", length = 35)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Column(name = "usr_modif")
	public Long getUsrModif() {
		return this.usrModif;
	}

	public void setUsrModif(Long usrModif) {
		this.usrModif = usrModif;
	}

	@Column(name = "orden_visual", nullable = false)
	public int getOrdenVisual() {
		return this.ordenVisual;
	}

	public void setOrdenVisual(int ordenVisual) {
		this.ordenVisual = ordenVisual;
	}

	@Column(name = "orden_calculo", nullable = false)
	public int getOrdenCalculo() {
		return this.ordenCalculo;
	}

	public void setOrdenCalculo(int ordenCalculo) {
		this.ordenCalculo = ordenCalculo;
	}


}
