package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SueConceptoForPago generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_for_pago")
public class SueConceptoForPago implements java.io.Serializable {

	private long conceptoFpId;
	private SueConceptoLey sueConceptoLey;
	private Long depId;
	private String monedaId;
	private BigDecimal porcentaje;
	private Date FDesde;
	private Date FHasta;

	public SueConceptoForPago() {
	}

	public SueConceptoForPago(long conceptoFpId, SueConceptoLey sueConceptoLey,
			String monedaId, BigDecimal porcentaje, Date FDesde) {
		this.conceptoFpId = conceptoFpId;
		this.sueConceptoLey = sueConceptoLey;
		this.monedaId = monedaId;
		this.porcentaje = porcentaje;
		this.FDesde = FDesde;
	}

	public SueConceptoForPago(long conceptoFpId, SueConceptoLey sueConceptoLey,
			Long depId, String monedaId, BigDecimal porcentaje, Date FDesde,
			Date FHasta) {
		this.conceptoFpId = conceptoFpId;
		this.sueConceptoLey = sueConceptoLey;
		this.depId = depId;
		this.monedaId = monedaId;
		this.porcentaje = porcentaje;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
	}

	@Id
	@Column(name = "concepto_fp_id", unique = true, nullable = false)
	public long getConceptoFpId() {
		return this.conceptoFpId;
	}

	public void setConceptoFpId(long conceptoFpId) {
		this.conceptoFpId = conceptoFpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@Column(name = "dep_id")
	public Long getDepId() {
		return this.depId;
	}

	public void setDepId(Long depId) {
		this.depId = depId;
	}

	@Column(name = "moneda_id", nullable = false, length = 15)
	public String getMonedaId() {
		return this.monedaId;
	}

	public void setMonedaId(String monedaId) {
		this.monedaId = monedaId;
	}

	@Column(name = "porcentaje", nullable = false, precision = 5)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

}
