package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SueConceptoPlantillaDetalle generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_plantilla_detalle")
public class SueConceptoPlantillaDetalle implements java.io.Serializable {

	private long plantillaDetalleId;
	private SueConceptoLey sueConceptoLey;
	private SueConceptoPlantilla sueConceptoPlantilla;
	private Date FDesde;
	private Date FHasta;
	private Date FCarga;
	private long usrCarga;
	private Date FModif;
	private Long usrModif;

	public SueConceptoPlantillaDetalle() {
	}

	public SueConceptoPlantillaDetalle(long plantillaDetalleId,
			SueConceptoLey sueConceptoLey,
			SueConceptoPlantilla sueConceptoPlantilla, Date FDesde,
			Date FCarga, long usrCarga) {
		this.plantillaDetalleId = plantillaDetalleId;
		this.sueConceptoLey = sueConceptoLey;
		this.sueConceptoPlantilla = sueConceptoPlantilla;
		this.FDesde = FDesde;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
	}

	public SueConceptoPlantillaDetalle(long plantillaDetalleId,
			SueConceptoLey sueConceptoLey,
			SueConceptoPlantilla sueConceptoPlantilla, Date FDesde,
			Date FHasta, Date FCarga, long usrCarga, Date FModif, Long usrModif) {
		this.plantillaDetalleId = plantillaDetalleId;
		this.sueConceptoLey = sueConceptoLey;
		this.sueConceptoPlantilla = sueConceptoPlantilla;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.FCarga = FCarga;
		this.usrCarga = usrCarga;
		this.FModif = FModif;
		this.usrModif = usrModif;
	}

	@Id
	@Column(name = "plantilla_detalle_id", unique = true, nullable = false)
	public long getPlantillaDetalleId() {
		return this.plantillaDetalleId;
	}

	public void setPlantillaDetalleId(long plantillaDetalleId) {
		this.plantillaDetalleId = plantillaDetalleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_ley_id", nullable = false)
	public SueConceptoLey getSueConceptoLey() {
		return this.sueConceptoLey;
	}

	public void setSueConceptoLey(SueConceptoLey sueConceptoLey) {
		this.sueConceptoLey = sueConceptoLey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plantilla_id", nullable = false)
	public SueConceptoPlantilla getSueConceptoPlantilla() {
		return this.sueConceptoPlantilla;
	}

	public void setSueConceptoPlantilla(
			SueConceptoPlantilla sueConceptoPlantilla) {
		this.sueConceptoPlantilla = sueConceptoPlantilla;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

	@Column(name = "f_carga", nullable = false, length = 35)
	public Date getFCarga() {
		return this.FCarga;
	}

	public void setFCarga(Date FCarga) {
		this.FCarga = FCarga;
	}

	@Column(name = "usr_carga", nullable = false)
	public long getUsrCarga() {
		return this.usrCarga;
	}

	public void setUsrCarga(long usrCarga) {
		this.usrCarga = usrCarga;
	}

	@Column(name = "f_modif", length = 35)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Column(name = "usr_modif")
	public Long getUsrModif() {
		return this.usrModif;
	}

	public void setUsrModif(Long usrModif) {
		this.usrModif = usrModif;
	}

}
