package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueConceptoCalculoTipo generated by hbm2java
 */
@Entity
@Table(name = "sue_concepto_calculo_tipo")
public class SueConceptoCalculoTipo implements java.io.Serializable {

	private String tipoCalculoId;
	private String descrip;
	private Set<SueConceptoCalculo> sueConceptoCalculos = new HashSet<SueConceptoCalculo>(
			0);

	public SueConceptoCalculoTipo() {
	}

	public SueConceptoCalculoTipo(String tipoCalculoId, String descrip) {
		this.tipoCalculoId = tipoCalculoId;
		this.descrip = descrip;
	}

	public SueConceptoCalculoTipo(String tipoCalculoId, String descrip,
			Set<SueConceptoCalculo> sueConceptoCalculos) {
		this.tipoCalculoId = tipoCalculoId;
		this.descrip = descrip;
		this.sueConceptoCalculos = sueConceptoCalculos;
	}

	@Id
	@Column(name = "tipo_calculo_id", unique = true, nullable = false, length = 15)
	public String getTipoCalculoId() {
		return this.tipoCalculoId;
	}

	public void setTipoCalculoId(String tipoCalculoId) {
		this.tipoCalculoId = tipoCalculoId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueConceptoCalculoTipo")
	public Set<SueConceptoCalculo> getSueConceptoCalculos() {
		return this.sueConceptoCalculos;
	}

	public void setSueConceptoCalculos(
			Set<SueConceptoCalculo> sueConceptoCalculos) {
		this.sueConceptoCalculos = sueConceptoCalculos;
	}

}
