package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SueModuloCoeficiente generated by hbm2java
 */
@Entity
@Table(name = "sue_modulo_coeficiente")
public class SueModuloCoeficiente implements java.io.Serializable {

	private short coeficienteId;
	private String descrip;
	private BigDecimal valor;
	private Date FDesde;
	private Date FHasta;

	public SueModuloCoeficiente() {
	}

	public SueModuloCoeficiente(short coeficienteId, String descrip,
			BigDecimal valor, Date FDesde) {
		this.coeficienteId = coeficienteId;
		this.descrip = descrip;
		this.valor = valor;
		this.FDesde = FDesde;
	}

	public SueModuloCoeficiente(short coeficienteId, String descrip,
			BigDecimal valor, Date FDesde, Date FHasta) {
		this.coeficienteId = coeficienteId;
		this.descrip = descrip;
		this.valor = valor;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
	}

	@Id
	@Column(name = "coeficiente_id", unique = true, nullable = false)
	public short getCoeficienteId() {
		return this.coeficienteId;
	}

	public void setCoeficienteId(short coeficienteId) {
		this.coeficienteId = coeficienteId;
	}

	@Column(name = "descrip", nullable = false, length = 150)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@Column(name = "valor", nullable = false, precision = 5)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "f_desde", nullable = false, length = 35)
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		this.FDesde = FDesde;
	}

	@Column(name = "f_hasta", length = 35)
	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		this.FHasta = FHasta;
	}

}
