package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SueValorBaseTipo generated by hbm2java
 */
@Entity
@Table(name = "sue_valor_base_tipo")
public class SueValorBaseTipo implements java.io.Serializable {

	private String tipoValorBaseId;
	private String descrip;
	private Set<SueValorBaseDetalle> sueValorBaseDetalles = new HashSet<SueValorBaseDetalle>(
			0);

	public SueValorBaseTipo() {
	}

	public SueValorBaseTipo(String tipoValorBaseId, String descrip) {
		this.tipoValorBaseId = tipoValorBaseId;
		this.descrip = descrip;
	}

	public SueValorBaseTipo(String tipoValorBaseId, String descrip,
			Set<SueValorBaseDetalle> sueValorBaseDetalles) {
		this.tipoValorBaseId = tipoValorBaseId;
		this.descrip = descrip;
		this.sueValorBaseDetalles = sueValorBaseDetalles;
	}

	@Id
	@Column(name = "tipo_valor_base_id", unique = true, nullable = false, length = 15)
	public String getTipoValorBaseId() {
		return this.tipoValorBaseId;
	}

	public void setTipoValorBaseId(String tipoValorBaseId) {
		this.tipoValorBaseId = tipoValorBaseId;
	}

	@Column(name = "descrip", nullable = false, length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sueValorBaseTipo")
	public Set<SueValorBaseDetalle> getSueValorBaseDetalles() {
		return this.sueValorBaseDetalles;
	}

	public void setSueValorBaseDetalles(
			Set<SueValorBaseDetalle> sueValorBaseDetalles) {
		this.sueValorBaseDetalles = sueValorBaseDetalles;
	}

}
