package ar.gob.gba.sg.dpsit.sueldos.model;

// Generated 15/07/2013 12:44:21 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SueValorBaseDetalle generated by hbm2java
 */
@Entity
@Table(name = "sue_valor_base_detalle")
public class SueValorBaseDetalle implements java.io.Serializable {

	private long valorBaseDetalleId;
	private SueRegimenLaboral sueRegimenLaboral;
	private SueValorBaseTipo sueValorBaseTipo;
	private String leyId;
	private long agrupamientoId;
	private long categoriaId;
	private BigDecimal valor;

	public SueValorBaseDetalle() {
	}

	public SueValorBaseDetalle(long valorBaseDetalleId,
			SueRegimenLaboral sueRegimenLaboral,
			SueValorBaseTipo sueValorBaseTipo, String leyId,
			long agrupamientoId, long categoriaId, BigDecimal valor) {
		this.valorBaseDetalleId = valorBaseDetalleId;
		this.sueRegimenLaboral = sueRegimenLaboral;
		this.sueValorBaseTipo = sueValorBaseTipo;
		this.leyId = leyId;
		this.agrupamientoId = agrupamientoId;
		this.categoriaId = categoriaId;
		this.valor = valor;
	}

	@Id
	@Column(name = "valor_base_detalle_id", unique = true, nullable = false)
	public long getValorBaseDetalleId() {
		return this.valorBaseDetalleId;
	}

	public void setValorBaseDetalleId(long valorBaseDetalleId) {
		this.valorBaseDetalleId = valorBaseDetalleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reg_laboral_id", nullable = false)
	public SueRegimenLaboral getSueRegimenLaboral() {
		return this.sueRegimenLaboral;
	}

	public void setSueRegimenLaboral(SueRegimenLaboral sueRegimenLaboral) {
		this.sueRegimenLaboral = sueRegimenLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_valor_base_id", nullable = false)
	public SueValorBaseTipo getSueValorBaseTipo() {
		return this.sueValorBaseTipo;
	}

	public void setSueValorBaseTipo(SueValorBaseTipo sueValorBaseTipo) {
		this.sueValorBaseTipo = sueValorBaseTipo;
	}

	@Column(name = "ley_id", nullable = false, length = 4)
	public String getLeyId() {
		return this.leyId;
	}

	public void setLeyId(String leyId) {
		this.leyId = leyId;
	}

	@Column(name = "agrupamiento_id", nullable = false)
	public long getAgrupamientoId() {
		return this.agrupamientoId;
	}

	public void setAgrupamientoId(long agrupamientoId) {
		this.agrupamientoId = agrupamientoId;
	}

	@Column(name = "categoria_id", nullable = false)
	public long getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(long categoriaId) {
		this.categoriaId = categoriaId;
	}

	@Column(name = "valor", nullable = false, precision = 15, scale = 5)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
